apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftControllerManagerConfig
build:
  buildDefaults:
    resources: {}
  imageTemplateFormat:
    format: ${DOCKER_BUILDER_IMAGE}
deployer:
  imageTemplateFormat:
    format: ${DEPLOYER_IMAGE}
dockerPullSecret:
  internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
ingress:
  ingressIPNetworkCIDR: ''
kubeClientConfig:
  kubeConfig: /etc/kubernetes/service-admin.kubeconfig
servingInfo:
  bindAddress: 0.0.0.0:8444
  bindNetwork: tcp4
  certFile: /etc/kubernetes/openshift-controller-manager-server.pem
  keyFile: /etc/kubernetes/openshift-controller-manager-server-key.pem
  clientCA: /etc/kubernetes/root-ca.pem
