#!/bin/bash

sudo podman pull --authfile pull-secret ${OPENSHIFT_CONTROLLER_MANAGER_IMAGE}

sudo podman run -d --rm --privileged --name openshift-controller-manager --network host \
  -v /etc/k8s/pki:/etc/kubernetes:Z \
  ${OPENSHIFT_CONTROLLER_MANAGER_IMAGE} \
  openshift-controller-manager start --config=/etc/kubernetes/config-openshiftController.yaml