apiVersion: v1
kind: Endpoints
metadata:
  name: openshift-apiserver
  namespace: default
subsets:
- addresses:
  - ip: ${EXTERNAL_API_IP_ADDRESS}
  ports:
  - name: https
    port: 4443
    protocol: TCP
