apiVersion: kubecontrolplane.config.openshift.io/v1
kind: KubeControllerManagerConfig
extendedArguments:
  authentication-kubeconfig:
  - "/etc/kubernetes/kube-controller-manager.kubeconfig"
  authorization-kubeconfig:
  - "/etc/kubernetes/kube-controller-manager.kubeconfig"
  allocate-node-cidrs:
  - 'true'
  cert-dir:
  - "/var/run/kubernetes"
  cluster-cidr:
  - ${POD_NETWORK_CIDR}
  cluster-signing-cert-file:
  - "/etc/kubernetes/root-ca.pem"
  cluster-signing-key-file:
  - "/etc/kubernetes/root-ca-key.pem"
  configure-cloud-routes:
  - 'false'
  controllers:
  - "*"
  - "-ttl"
  - "-bootstrapsigner"
  - "-tokencleaner"
  enable-dynamic-provisioning:
  - 'true'
  experimental-cluster-signing-duration:
  - 720h
  feature-gates:
  - ExperimentalCriticalPodAnnotation=true
  - RotateKubeletServerCertificate=true
  - SupportPodPidsLimit=true
  - LocalStorageCapacityIsolation=false
  flex-volume-plugin-dir:
  - "/etc/kubernetes/kubelet-plugins/volume/exec"
  kube-api-burst:
  - '300'
  kube-api-qps:
  - '150'
  leader-elect-resource-lock:
  - configmaps
  leader-elect:
  - 'true'
  leader-elect-retry-period:
  - 3s
  port:
  - '0'
  root-ca-file:
  - "/etc/kubernetes/root-ca.pem"
  secure-port:
  - '10252'
  service-account-private-key-file:
  - "/etc/kubernetes/service-account-key.pem"
  service-cluster-ip-range:
  - ${SERVICE_NETWORK_CIDR}
  use-service-account-credentials:
  - 'true'
serviceServingCert:
  certFile: "/etc/kubernetes/root-ca.pem"
