#!/bin/bash

sudo podman pull --authfile pull-secret ${HYPERKUBE_IMAGE}

sudo podman run -d --rm --name kube-controller-manager --network host \
  -v /etc/k8s/base/kube-apiserver:/etc/kubernetes:Z \
  ${HYPERKUBE_IMAGE} \
  hyperkube kube-controller-manager --openshift-config=/etc/kubernetes/config-controller.yaml --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig